name: Notifications

on:
  pull_request:
    types:
      - closed
  
jobs:
  notifications:
    # Run whenever next-paper labelled PR is merged to main branch
    if: ${{ github.event.pull_request.merged == true &&
            contains(github.event.pull_request.labels.*.name, 'next-paper') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: cat data/vars.txt >> $GITHUB_OUTPUT
      - uses: Ilshidur/action-discord@master
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        with:
          args: ${{ fromJSON(steps.vars.outputs.discordNext) }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
